### PR TITLE
Add syntax files for common editors

### LINKED ISSUE #42: PP supports in editors
Hello :-),

Supported editors:
  * Emacs, https://github.com/stevenremot/hoa-pp-mode,
  * Vim, https://github.com/Hywan/Dotfiles/blob/master/vim/syntax/pp.vim.

Should we add these resources in this library or in [`Hoa\Devtools`](http://central.hoa-project.net/Resource/Library/Devtools) @hoaproject/hoackers?

### PR DESCRIPTION
**Pull request by jubianchi**
* Vim and Neovim (thanks @Hywan)
* Emacs (thanks @stevenremot)

Closes #42

### CODE REVIEW

**Comment by Hywan** [comment]
Why one file for Vim and another one for Neovim? There are the same.

Also, we discussed with @vonglasow about creating a contribution repository for these files. I am assigning him for this issue and explain our thoughts.

**Comment by stevenremot** [comment]
Hi,

I'm glad my work have some value to you! I just wanted to let you know, if you don't use Emacs, that it is shipped with its own package manager, and that my package is registered in MELPA, a popular package repository (http://melpa.org/#/hoa-pp-mode).

It is nice to provide this Emacs package directly in your resources, but it may be easier for you (and maybe more convenient for Emacsers) to let interested people know there is a package on MELPA that adds PP grammars support to Emacs in one way or another. I'm here to help you on this subject if necesary.

**Comment by Hywan** [comment]
@stevenremot This is exactly what we talked with @vonglasow. Instead of adding these resources in `Hoa\Compiler` or `Hoa\Devtools`, we think this is better to have unique repository to be plugged easily with editor plugin managers (Melpa for Emacs, Vundle for Vim etc.). And then, to promote then, we can add mentions on `Hoa\Compiler` or `Hoa\Devtools`' documentations. For instance, we also have `_hoa` for Zsh autocompletion for `Hoa\Cli` (https://github.com/Hywan/Dotfiles/blob/master/zsh/_hoa).

So, what about the following new repositories:
* `Contributions/Vim/Pp`,
* `Contributions/Emacs/Pp`,
* `Contributions/Zsh/Hoa`.

Thoughts?

**Comment by Hywan** [comment]
(repository names are just draft).

@stevenremot Thank you for your contribution!

**Comment by Hywan** [comment]
@stevenremot How do you feel to lead the Emacs repository?

**Comment by Hywan** [comment]
@stevenremot How do you feel to lead the Emacs repository?

**Comment by Hywan** [comment]
(sorry, missclick…)

**Comment by stevenremot** [comment]
> So, what about the following new repositories:
>
>    Contributions/Vim/Pp,
>    Contributions/Emacs/Pp,
>    Contributions/Zsh/Hoa.
>
> Thoughts?

Sounds good to me. If I understand correctly, these repositories contaisn instructions to add Pp support for each editor, no code ?

> @stevenremot How do you feel to lead the Emacs repository?

I'm willing to lead it if you don't already have someone more qualified on the hand.

**Comment by Hywan** [comment]
@stevenremot I need your SSH key.
These repositories will contain the Vim, Emacs, Zsh etc. code. They will be standalone repositories, so it will be easier to include them on vimawesome.org, meltpa.org etc. Thoughts?

**Comment by Hywan** [comment]
@stevenremot Which one shoud I take https://github.com/stevenremot.keys?

**Comment by stevenremot** [comment]
Ok, so my repository will be moved to a new one under the hoa organization ? I'm fine with it.

You can take the third key.

**Comment by Hywan** [comment]
Here we are:
* Emacs/Pp:
  * http://git.hoa-project.net/Contributions/Emacs/Pp.git/,
  * https://github.com/hoaproject/Contributions-Emacs-Pp/,
  * https://github.com/orgs/hoaproject/teams/contributions-emacs.
* Vim/Pp:
  * http://git.hoa-project.net/Contributions/Vim/Pp.git/,
  * https://github.com/hoaproject/Contributions-Vim-Pp/,
  * https://github.com/orgs/hoaproject/teams/contributions-vim.
* Zsh/Hoa:
  * http://git.hoa-project.net/Contributions/Zsh/Hoa.git/,
  * https://github.com/hoaproject/Contributions-Zsh-Hoa,
  * https://github.com/orgs/hoaproject/teams/contributions-zsh.

They are all preliminary repositories. Feel free to PR, plug everything on existing plugin managers & co.

@stevenremot: To start, I guess this is better to make PR on the Emacs/Pp repository. I am not sure about the licence. I just used the commit from @jubianchi. I am adding your SSH key right now, but don't push on Github, this is a mirror. Come on #hoaproject (Freenode) to get more information about the workflow (you can start with http://hoa-project.net/En/Literature/Contributor/Guide.html)!

**Comment by Hywan** [comment]
Welcome on board @stevenremot: http://hoa-project.net/Community.html#Contributors!

**Comment by jubianchi** [comment]
:+1: 

Welcome @stevenremot and thanks for your work on Emacs!

**Comment by Hywan** [comment]
@jubianchi You would you like to be part of the @hoaproject/contributions-emacs team too? Sorry for not asking before…

**Comment by jubianchi** [comment]
@hywan no problem ;)

If you need some help there, mainly on issues triaging and support, why not :)

But I'm not an emacs user and my knowledge of it is limited.

**Comment by Hywan** [comment]
@jubianchi Done, welcome on board!

**Comment by stevenremot** [comment]
Thanks for including me to the project! I have read the contribution guide and will start to write issues and PRs today.

**Comment by Hywan** [comment]
@stevenremot Perfect :-].

**Comment by Hywan** [comment]
The [Vim plugin](https://github.com/hoaproject/Contributions-Vim-Pp) is over and [it works](https://github.com/Hywan/Dotfiles/commit/61cf828539812a8aeb7e7a5a01fcdfb69285362a).

**Pull request closed without merging**
